# Generated by Django 6.0.7 on 2026-07-22 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="payment_date",
        ),
    ]
